### ISSUE TITLE
Modding and PR's

### ISSUE THREAD

**Issue by Wyn-Price** [jredfox/evilnotchlib#1]
This is coming from [here](https://github.com/Angry-Pixel/The-Betweenlands/pull/579).

You shouldn't do a PR on someone else's mod if you know you can solve the issue yourself. Like many people have said, you shouldn't go through every mod adding soft dep just to make it work. The best solution would be [this](https://github.com/Angry-Pixel/The-Betweenlands/pull/579#issuecomment-382285498), but if you're so against that (which I don't know why you would be) then just add a config with a String array for the classnames of the guis you want to include. There are plenty of ways you can do this without making PRs to all the mods (or 400+ as you say), that's just insane. 
> there is nothing flawed about evil notch lib there is plenty with forge.

There is most definitely stuff wrong with evil notch lib. I spent less a few minutes looking around "evil notch lib" and found multiple things wrong. Firstly, in your [BlockAPI.java](https://github.com/jredfox/evilnotchlib/blob/caf782aa7da35aa105fd7f6992c7041b44943619/src/main/java/com/EvilNotch/lib/Api/BlockApi.java), you are trying to set/get the blocks hardness, soundtype, harvestLevel, stuff like that from the field. This will not always work. There are getter methods in the Block Class that override the getter for just the field. If a mod overrides them, and doesn't set the field value, your mod will break and get the wrong thing. Before you say how a mod should do that to make it compatible with your mod. No. That's not how it should work. You can't make a flawed system then complain when other mods don't change THEIR system to fit with YOUR broken system. When SecretRoomsMod didn't work with CTM, I didn't make a PR to rewrite CTMs baked quad stuff, I just changed my system to make it work with CTM, and that's something you should be doing. Rather than make a broken system and get other mods to work with it, make a working system that has no trouble with other mods.

Another issue I have is your [BasicModel.java](https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/EvilNotch/lib/minecraft/content/client/models/BasicModel.java). From what it looks like, you're trying to change the texture of the model. This. Will. Not. Work. The texture of the quad that's being rendered is not held in the IBakedModels sprite, its held in the vertex data of each BakedQuad in the list. If you want to retexture a model, just use BakedQuadRetextured on all the quads.

Your [FakeWorld.java](https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/EvilNotch/lib/minecraft/content/FakeWorld.java) is not very threadsafe. You're caching the entities into static maps. Please read [HERE](https://www.journaldev.com/1061/thread-safety-in-java) and actually get to understand thread saftey, because you clearly don't have any idea of what it means. You are literally storing every entity in the main thread fake world. You're caching entities to your fake world only when the first `WorldEvent.Load` is fired. You do understand that every dimension is its own world class. And that on a server, there will be multiple worlds. You can't just set a static field to the world that's first called in `WorldEvent.Load`.

Another thing wrong with your lib, is that [it is inside iteself](https://github.com/jredfox/evilnotchlib/tree/4c88d2b97fe102f498611ce4e3de2fe65a5b567d/src/main/java/com/EvilNotch/lib/util/src/main/java/com/EvilNotch/lib). I get this is probably a mistake. but accidentally copying your workspace into itself, then going online to brag about how your mod `[has] nothing flawed` are not things that add up.

Finally, there is no reason that your [build.gradle Lines 14-16](https://github.com/jredfox/evilnotchlib/blob/master/build.gradle#L14-L16)
should be like this:
```gradle
version = "1.0"
group = "com.yourname.modid" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "modid"
```
You should definitely change that, ~~most~~ all mod tutorials tell you to change that. It's just dumb to have to manually change the file name each time.

Apart from the amount of empty files. ([here](https://github.com/jredfox/EvilNotchCore/blob/master/src/main/java/com/EvilNotch/Core/asm/CoreModLoader.java) and [here](https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/EvilNotch/lib/Api/NBTPathApi.java) are the ones i could be bothered to find), and the fact you've used your own `.gitignore`, meaning its much more difficult for people to set up their own PR's, or even load your code into a workspace, evil notch lib isnt that good. The intent behind it look like good, and you have some promising ideas, but it's obvious from looking through your code that its a bunch of tutorials and copypaste mixed into one unholy mess.

I'm not trying to make you feel bad about your code, sure if you look through my code, you'll probably find things that are pretty bad and could be improved (especially with srm), but I understand that my code isn't the best, and I certainly don't brag about how it is flawless, when it clearly isn't. I can also take criticism well, and from what I've read so far from this PR you can't. Someone saying your code isn't bad is not something to be offended about. As cringy as it sounds, you should use the criticism to help yourself get better, not just make yourself look more childish. Your tone throughout this whole PR has been condescending. You have to remember, you are not doing TheCyberBrick or "chimp" a favour by doing this. Noone was going to them asking for support for your mod. You decided to make a PR to THEIR mod to change THEIR code. You have to impress them and try and make them pull, not just think that because you have a mod with 3,375 (at the time of writing this) that you feel the need to try and one up them. I'm not trying to make you feel bad with this, Im just trying to explain that evilnotchlib is not as perfect as you assume it to be, and neither are you. I think you've just fallen a victim to the Dunning-Kruger effect.

![image](https://user-images.githubusercontent.com/15876682/38943139-92e039bc-4328-11e8-9212-82d677a353eb.png)
Also, aren't you the guy that came onto the moddingmc discord, complaining that you want to do model stuff without using jsons. Told everyone that `once a mod is compiled the resources of jsons would be located in the jar if the application closes in the middle of it the jar could corrupt`, something you obviously don't understand yourself, because that is wrong on so many levels. You thought that `IBakedModel#getSprite` was what's rendered, even though you were told countless times (by me and other people) that the real texture is in the vertex data, then to ask if we're all sure that that's how it is. (It is like that). You then say `because I am coding a library if I decide to make a mod that adds 10,000 randomized blocks using my lib into the game with random properties I don't want the game taking a minuet extra parsing the jsons`. When you were told countless times to just use BASIC python to create all the models and stuff you say you `want to do it the hard way`. When everyone was telling you that you were doing it wrong, you go
> so none of you all gave me any straight answers and constricted each other I assume you have never done a custom model before

to the whole group You then try and be condescending and go `ok sorry`, then after litral seconds asking that same person to solve your xy problem. You then left for a couple of hours, came back, asked the exact same question again, got called to `stop being stupid`,  pinged the mods because you got called stupid, the mods told you to fuck off, you then told the mods that people were you stupid, mods told you to stop pinging them and to act normal, then to say `I came here to code not be harassed by someone how doesn't even know that much code.` (You seems to follow that condescending theme). You then tell people their wrong as `you all use an api for recipes IRecipe` and `everything turns into that eventually`, until then leaving. 

If you can’t handle criticism or people better than you telling you you're doing something wrong, don't even bother modding.

**Comment by jredfox** [comment]
your a fucking moring tell the fucking betweenlands to register their own goddam menu.

YOU CANNOT FUCKING AUTO DETECT MENUS THEY HAVE TO BE HARD CODED THEIR IS NO FUCKING ARRAY SO I MADE THEM

**Comment by jredfox** [comment]
AND I WON't MANUALLY SUPPORT EVERY GODAM MOD THAT REFUSES TO REGISTER
