### ISSUE TITLE
IItemRender Incompatibilities

### ISSUE THREAD

**Issue by chimericdream** [jredfox/evilnotchlib#11]
**Issue:** When I try to install this mod into my pack, the textures for ender chests/tanks and for /dank/null items turn invisible.

**Version:** 1.2.3-SNAPSHOT-66

**Steps to reproduce:**
1. Install the mods below in a minimal profile
1. Start game
1. Open inventory and search JEI for "dank" or "ender"

**ModPack/ModList:**
* forge-14.23.4.2759
* DankNull-1.12-1.4.33
* CodeChickenLib-1.12.2-3.2.1.351-universal
* EnderStorage-1.12.2-2.4.5.135-universal
* EvilNotchLib-1.2.3-SNAPSHOT-66
* jei_1.12.2-4.11.0.212
* p455w0rdslib-1.12-2.0.33

**Screenshots:**
![2018-09-02_12 49 28](https://user-images.githubusercontent.com/198075/44959135-a70da800-aeaf-11e8-9555-4a7fac950b10.png)
![2018-09-02_12 49 29](https://user-images.githubusercontent.com/198075/44959136-a70da800-aeaf-11e8-881e-a57fc0e5ea1c.png)
![2018-09-02_12 49 38](https://user-images.githubusercontent.com/198075/44959137-a70da800-aeaf-11e8-8d24-e35bd2b9011b.png)
![2018-09-02_12 49 40](https://user-images.githubusercontent.com/198075/44959138-a70da800-aeaf-11e8-85ce-963f0d0d622b.png)
![2018-09-02_12 49 41](https://user-images.githubusercontent.com/198075/44959139-a70da800-aeaf-11e8-9790-29fd15d07550.png)

**Screenshot without this mod:**
![2018-09-02_13 04 07](https://user-images.githubusercontent.com/198075/44959306-a70ea780-aeb1-11e8-9ff1-4148199f3be5.png)

**Comment by jredfox** [comment]
I will try to ping elix_x as he is the creator but, it might be a couple weeks before I can safely fix and make edits to it without screwing literally everything up.

**Comment by chimericdream** [comment]
Understandable. I just checked with snapshot 44 per your suggestion in the other thread. The textures show up, but the Silk Spawners mod is no longer compatible. If I want to use the Silk Spawners, should I stick with 1.2.02 of ENL and 1.7 of SS until this is resolved?

**Comment by jredfox** [comment]
if you want silkspawners for now backport to 1.6x or 1.7 without the iitemerender. now 1.7 requires a very specific build if you don't want the iitemrender to make your textures invisible 

sadley there is no renderers for this 1.8 was the render update. 

1.7 had dynamic translations but, issues with sub mob names. 1.6 has no issues if your language is english or not on a dedicated server

**Comment by chimericdream** [comment]
Will do, thanks! I'll keep an eye on this thread. I understand how real life is, and as a programmer myself I understand that bugs are rarely easy enough to fix overnight.

**Comment by jredfox** [comment]
do you want to try and fix this issue for me. It would get fixed alot faster here is the mod's good that would mean sooo much to me. I am drowning in code right now and am unable to get to this issue at this current week-two.
https://github.com/jredfox/evilnotchlib/tree/master/src/main/java/com/elix_x/itemrender

list of issues for IITemRenderer possibly:
mipmap might not be proper need to restore it before and after rendering an item????
the incompatiblility with other mods
I am unsure why there is ground transformation in the code could be creating issues I cannot directly easily see

**Comment by chimericdream** [comment]
I can take a stab at it, yeah. I can't promise I'll fix it faster than you, but no harm in taking a look.

**Comment by jredfox** [comment]
No rush but, do you think you can spot the issue by next weak @chimericdream  please and thanks

**Comment by Shadows-of-Fire** [comment]
You should not be hacking back in an IItemRenderer.  Use TileEntityItemStackRenderer.

**Comment by jredfox** [comment]
"TileEntityItemStackRenderer" doesn't provide nbt nore the itemstack or even the item

**Comment by Shadows-of-Fire** [comment]
It provides the stack, what are you on about?

**Comment by jredfox** [comment]
TESR Stack fires your render with a null tile entity and no nbt

**Comment by Shadows-of-Fire** [comment]
Thats the deprecated system, not TileEntityItemStackRenderer

**Comment by Shadows-of-Fire** [comment]
https://mcforge.readthedocs.io/en/latest/rendering/teisr/

**Comment by jredfox** [comment]
it's the same dam system the difference is it creates a tile object and uses the same render for the block. I don't want the exact same render I could return a new render but, still doesn't provide any nbt

**Comment by Shadows-of-Fire** [comment]
Read the link

**Comment by jredfox** [comment]
link doesn't state how to get the nbt of the stack that was last used. you can look at forge source they don't provide the nessary interface between tile with data and stack that's it's attempting to render.

Furthermore it was designed for the exact same render as the ground not a separate render for the inventory which Is what I am doing two separate renders. Thus lack of nbt and the design itself being wrong for silkspawners it's currently impossible without using the ported lib by elix_x

**Comment by Shadows-of-Fire** [comment]
You literally get the stack... the nbt is on it

**Comment by jredfox** [comment]
forge hooks freaken null. look at the actual call they do for their render there is no stack at this point only a null tile entity

   ` public static void renderTileItem(Item item, int metadata)
    {
        Class<? extends TileEntity> tileClass = tileItemMap.get(Pair.of(item, metadata));
        if (tileClass != null)
        {
            TileEntitySpecialRenderer<?> r = TileEntityRendererDispatcher.instance.getRenderer(tileClass);
            if (r != null)
            {
                r.render(null, 0, 0, 0, 0, -1, 0.0F);
            }
        }
    }`

**Comment by Shadows-of-Fire** [comment]
Did you even look at that link?  Your paste is from the deprecated system.  TileEntityItemStackRenderer is a class, and it has no relation to the old system.

**Comment by jredfox** [comment]
I went ahead and looked at the classes all of them no itemstack is passed in anywhere accept for vanilla's hard coded if else branch but forge's actual call is null on the tile

**Comment by Shadows-of-Fire** [comment]
`TileEntityItemStackRenderer#renderByItem(ItemStack)`

**Comment by jredfox** [comment]
@chimericdream it appears the issue of replacement isn't a proper way of going about it. We might need to just asm the base class but, that still might not fire my things if the code chicken lib does the same thing

**Comment by jredfox** [comment]
Issue has bridged with code chicken lib we are going to talk it out. I don't like his interface as much as elix_x's so hopefully we could add compatibility.

**Comment by covers1624** [comment]
You really don't understand what the issue here is, you simply arent overriding RenderItem properly, if you grab the current RenderItem, and then inject yours and delegate to the RenderItem you grabbed, multiple overrides can co-exist, its been done before and its not rocket science. Also as @Shadows-of-Fire pointed out, Forge now has direct hooks for this.

**Comment by jredfox** [comment]
@covers1624 Well paleo said you were completely overriding it and some other people. 

I will look into it. Is the camera type there though? Regardless I see your point of completely overriding it is wrong even using asm at this point to edit the class would be better. I will try to look at and use what you have

**Comment by jredfox** [comment]
adding the implementation of elix's version is going to be difficult while still being mod compatible. I would need several places injected via lines. Might be a few days before this gets fixed. 

I plan on editing the base class in mdk till it is working then translating it into asm

**Comment by jredfox** [comment]
fixed no asm used wrapper class and access transformer.
