### ISSUE TITLE
Derp Debug not cleaned Up In SNAPSHOT 67

### ISSUE THREAD

**Issue by jprocket45** [jredfox/evilnotchlib#12]
Version:1.2.3 Snapshot 67
Issue:server crashes when starting up
Steps to reproduce:install EvilNotchLib 67 on server and it crashes
CrashReport/Log: https://pastebin.com/cvDtjJme
ModPack/ModList: lib only

forgive me if this was not fixed not trying to be a pain just reporting in case you thought it was fixed.

**Comment by jredfox** [comment]
separate issue try 66 if it does I have already fixed it. I was debugging and forgot to remove the lines before compiling it. I had already removed it in yesterday's 12 hour cleanup but, apparently not in the release.

**Comment by jredfox** [comment]
bugs are never a pain unless your in the middle of drowning in asm and 10 are reported half by you. That was three days ago and last week I can take 20 bugs right now without being a pain

**Comment by jredfox** [comment]
going to assume its fixed for next versions and was not there in snapshot 66

**Comment by jredfox** [comment]
snapshot 68 and 69 are pushed or being pushed right now. They no longer have this issue
