### ISSUE TITLE
IItemRender JEI Incompatability

### ISSUE THREAD

**Issue by jredfox** [jredfox/evilnotchlib#14]
Version:IItemRenderer 1.1
Issue:jei doesn't fire the IItemRenderer with silkspawners
Steps to reproduce:
install silkspanwers
observe no items in the tab

**Comment by jredfox** [comment]
might not be able to add support jei is directly calling the wrong methods. unless your code is specifically a TESR it doesn't work

**Comment by mezz** [comment]
More information here: https://github.com/mezz/JustEnoughItems/issues/1347
I think you just need to set `IBakedModel#isBuiltInRenderer` to `true` and it should work fine.

**Comment by jredfox** [comment]
hi @mezz I don't bake any models nor do I use a TESR. the mod that elix_x originally wrote was so you didn't have to make a TESR or bake any models by rendering `pre and post logic`. It also has the ability to cancel the render during the pre phase.

Because of the IItemRenderer  design I would prefer to leave it that way. Basically I have a few issues with jei. 

- one: since you directly call bake model it doesn't invoke my render item
- two: once I override a RenderItem#renderModel() my entity renders were offset by 0.5,0.5,0.5 translation and didn't have said issue rendering in the guis or any other transform types
- three: I have mip map issues that could be or could not be related to your jei basically it doesn't render the block properly and look solish rather then a spawner. *If you set your mip map to false,false,false before rendering I shouldn't have any issues*

Code:
https://github.com/jredfox/evilnotchlib/tree/master/src/main/java/com/elix_x/itemrender
Silkspawners implementation:
https://github.com/jredfox/silkspawners_rewrite/blob/master/src/main/java/com/EvilNotch/silkspawners/client/render/item/MobSpawnerItemRender.java

What Could you do?:
- tell me why the translations are off on my silkspawners entity render by 0.5 translations on xyz but, not off by 0.5 on the block. *I would like to fix this properly*
- could you add a blacklist that will render into the gui normally? As long as the params are the same my RenderItem object should work.I then could register all regsitered IItemRender instances to your blacklist since there is a hashmap between item and renderer. I would prefer to do this in post init
- mip map issues? during the silkspawners renderer it works with mip maps just fine but, in your jei tab every render after the first one looks oblique maybe if it's in a blacklist fix this. I don't know the exact open gl code.

Thanks for your time

**Comment by jredfox** [comment]
all render issues have been fixed and proper. The PR is pending but, besides that this issue is fixed.

**Comment by jredfox** [comment]
side is on jei's I can't truly fix this only edit is class with asm.
