### ISSUE TITLE
Snapshot 44 causing game hang

### ISSUE THREAD

**Issue by Nexusdog** [jredfox/evilnotchlib#2]
MC/F 1.12.2/2689, 2691

I can't provide a crash report or log as none are generated, apologies.

Game starts from launcher, game menu activates. Loading a saved world, the screen hangs at the '0%' screen and never recovers, requiring task manager to end process.

**Comment by jredfox** [comment]
with what mods? what dimension where you in? I am thinking that the issue could be the world dir is returning null or for some reason the entity not even on tick on the cache is throwing it's own exception

post log. logs are always generated even if the game crashes go to .minecraft > logs > organize by date modified > give me the latest file that had been launched after you reproduce the bug

Also take evil notch lib out does it still happen? does back porting your forge to 1.12.2 - 14.23.3.2655 fix the issue? **remove silkspawners for beta evil notch lib**.

**Comment by jredfox** [comment]
feedback is required in order for me to reproduce the bug to fix it

**Comment by jredfox** [comment]
Unable to reproduce I asked for your mod list which you had, a log which you do have, and feedback necessary for stuff which you didn't do

**Comment by jredfox** [comment]
seriously feedback required means provide latest crash log which always generates even if the game just freezes and modpack link/modlist is required

**Comment by jredfox** [comment]
so yeah that's why your issues always get closed you don't give the info that you have I gave you two things. Thus I cannot be sure it's even my mods issue
