### ISSUE TITLE
Fetching MCPMappings Path is almost Hardcoded

### ISSUE THREAD

**Issue by Niko-sk2x** [jredfox/evilnotchlib#80]
Instead of trying to use almost hardcoded path, it would work way better if it used `System.getProperty("net.minecraftforge.gradle.GradleStart.srg.srg-mcp");`

**Comment by jredfox** [comment]
I will check this out

**Comment by jredfox** [comment]
lib is getting re-written and implemented into my mod loader so we don't have to deal with this bs anymore
