### ISSUE TITLE
TF Naga is just a head, no segments, when Evilnotchlib is installed

### ISSUE THREAD

**Issue by BugmanBugman** [jredfox/evilnotchlib#81]
Version: EvilNotchLib-SNAPSHOT-103
Issue: 
![2020-03-26_20 26 31](https://user-images.githubusercontent.com/40730042/77712080-bfb54580-6fa0-11ea-8932-e8dfe351310e.png)

Steps to reproduce: download TF and ENL, and start up minecraft. spawn a naga
CrashReport/Log: users always have logs even if it doesn't crash
ModPack/ModList: just TF and Evil Notch lib

**Comment by jredfox** [comment]
provide log file
does it happen without the lib

**Comment by jredfox** [comment]
looking into this now

**Comment by jredfox** [comment]
Evil notch lib in this version was high wip trying to work around forge's bs. I have a re-write for it but, as for the 1.12x will not be fixed unless I make a forge port of my mod loader api's or partial apis to forge 1.12.2 as It's too much work just to fix this shit

**Comment by jredfox** [comment]
Issue has been fixed in the latest commit

**Comment by BugmanBugman** [comment]
holy shit what a blast from the past I was still in high school during quarantine
