### ISSUE TITLE
[1.7.10] Crash upon startup [java.lang.RuntimeException: LaunchClassLoader is unoptimized!]

### ISSUE THREAD

**Issue by aking4125** [jredfox/evilnotchlib#82]
**Version:** _evilnotchlib-a109.jar_

**Issue:** _Crash upon startup. This is required for Config Helper. Possibly more related to that mod?_

**Steps to reproduce:** _There much be a conflict somewhere. I just launch the game and boom_

**CrashReport/Log:**  [crash-2022-04-12_01.10.52-client.txt](https://github.com/jredfox/evilnotchlib/files/8469773/crash-2022-04-12_01.10.52-client.txt)

**Comment by jredfox** [comment]
Exactly what it says evil notch lib failed to initialize the launch class loader to prevent memory leaks. Try disabling foamfix it's not needed for 1.7.10 evil notch lib and optifine does this for you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Angel Rodriguez ***@***.***>
Sent: Tuesday, April 12, 2022 12:21:33 AM
To: jredfox/evilnotchlib ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jredfox/evilnotchlib] [1.7.10] Crash upon startup [java.lang.RuntimeException: LaunchClassLoader is unoptimized!] (Issue #82)


Version: evilnotchlib-a109.jar

Issue: Crash upon startup. This is required for Config Helper. Possibly more related to that mod?

Steps to reproduce: There much be a conflict somewhere. I just launch the game and boom

CrashReport/Log: crash-2022-04-12_01.10.52-client.txt<https://github.com/jredfox/evilnotchlib/files/8469773/crash-2022-04-12_01.10.52-client.txt>

**Comment by jredfox** [comment]
confirmed foamfix disable this in their config. they fix the bugs improper when mine simply provides empty dummy maps that cannot add anything to them to begin with. **personally I would remove foamfix as I don't trust mods that claim they fix things and then don't**. 
```
launchwrapper {
    # Remove LaunchWrapper package manifest map (which is not used anyway).
    B:removePackageManifestMap=false

    # Weaken LaunchWrapper's byte[] resource cache to make it cleanuppable by the GC. Safe.
    B:weakenResourceCache=false
}
```
